#!/usr/bin/env bash

for path in $(find ../google-fonts/* -maxdepth 0 -type d); do
  basepath="$(basename -- $path)"
  mkdir -p $basepath
  echo "> processing directory $basepath"

  for file in $(find $path/* -maxdepth 0); do
    basename="$(basename -- $file)"
    filename="${basename%.ttf}"
    extension="${basename##*.}"

    if [ "$extension" == "ttf" ] || [ "$extension" == "otf" ]
    then
      echo "  - convert $file into .af"
      ../afinate --quiet --quality medium --font $file $basepath/$filename.af
    else
      cp $file $basepath/$filename
      echo "  - copy $file"
    fi
  done
done
